image: node

stages:
  - build

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
  artifacts:  
    expire_in: 1 week
    paths:
      - dist
